add_newline = true
format = """
($git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$aws\
$kubernetes\
\n)\
$directory\
$time\
$character"""

[aws]
format = '([$symbol($profile )(\($region\) )]($style))'

[aws.region_aliases]
eu-central-1 = ''

[directory]
truncation_length = 2
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch]($style) "
only_attached = true

[git_status]
format = '(\[$all_status$ahead_behind\] )'
conflicted = '[!](bold red)'
modified = '[*](bold red)'
untracked = '[?](bold red)'
stashed = '[\$](bold blue)'
staged = '[+](bold green)'
renamed = '[»](bold green)'
deleted = '[-](bold red)'

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style)'

[kubernetes.context_aliases]
'arn:.*:cluster/(?P<cluster>[\w-]+)' = '$cluster'

[ruby]
version_format = '${major}.${minor}'

[time]
disabled = false
format = '[$time]($style)'
time_format = '%H:%M'
